FROM python:3.10-slim
WORKDIR /app

RUN apt-get update && \
    apt-get install -y git curl && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY dash/ dash/

EXPOSE 8501
CMD ["streamlit", "run", "dash/main.py", "--server.port=8501", "--server.address=0.0.0.0"]
